jenkinsci/eiffel-broadcaster-plugin

src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Util.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelEvent.java

1) Reformat purl in data.identity to allow for easier parsing to extract the Jenkins build path
2) Add "JENKINS_EIFFEL_BROADCASTER" as meta.source.name to make it easier for other Eiffel actors to identify events coming from this plugin.

Reformat purl and add meta.source.name

---

pom.xml

Maven 3.6 and findbugs-maven-plugin 3.0.1 results in the following error:
[2020-02-29T20:52:59.072Z] [ERROR] Failed to execute goal org.codehaus.mojo:findbugs-maven-plugin:3.0.1:findbugs (findbugs) on project eiffel-broadcaster: Unable to parse configuration of mojo org.codehaus.mojo:findbugs-maven-plugin:3.0.1:findbugs for parameter pluginArtifacts: Cannot assign configuration entry 'pluginArtifacts' with value '${plugin.artifacts}' of type java.util.Collections.UnmodifiableRandomAccessList to property of type java.util.ArrayList -> [Help 1]
Guided by https://stackoverflow.com/a/55834783 the plugin is upgraded to the latest version.

pom.xml: Upgrade findbugs-maven-plugin to fix build error

---

pom.xml
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelBroadcasterConfig.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelJobTable.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/ItemListenerImpl.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/MQConnection.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/QueueListenerImpl.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/RunListenerImpl.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Util.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityCanceledEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityFinishedEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityStartedEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityTriggeredEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelEvent.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EmittedEventsTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EventSet.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Matchers.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Mocks.java

This PR adds tests to check the contents of the emitted events for a couple of common job types (freestyle, matrix, pipeline). To make writing the tests less painful the event classes are refactored to actually model the Eiffel events instead of storing the event data in hashmaps. This should also simplify future expansions of the event contents (causes etc) and make it less error-prone. Fixes #13.
I'm sorry for this huge PR, but I've at least tried to split all logical changes into different commits. I recommend that you look at the individual commits rather than the diff of the whole PR.

Introduce tests of emitted events and fix a few bugs found along the way

---

pom.xml
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelActivityTriggerAction.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/QueueListenerImpl.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EmittedEventsTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Matchers.java

When a build is enqueued, populate the ActT event's data.trigger attribute with objects translated from the build's causes. We currently support TimerTriggerCause, SCMTriggerCause, and UpstreamCause. The first two ones are quite straightforward and only involves setting the trigger type (to TIMER and SOURCE_CHANGE, respectively) but the UpstreamCause requires some work.
Jenkins can tell us which build triggered the current build, but what we're interested in is the ID of that build's ActT event since that's what should end up in the CAUSE link. We introduce a new action for this, EiffelActivityTriggerAction, which also makes the ActT event available to the outside world (via e.g. the $BUILD_URL/api/json endpoint). We'll also have use for it when we implement issue #20.
Fixes #11.

Add trigger information to the ActT events

---

src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/RunListenerImpl.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityFinishedEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityStartedEvent.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EmittedEventsTest.java

Populate the data.executionUri and data.liveLogs members of ActS and data.persistentLogs member of ActF in RunListenerImpl. Fixes #12.

Include build and log URIs in ActS and ActF

---

src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityCanceledEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityFinishedEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityStartedEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityTriggeredEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/InvalidJsonPayloadException.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/UnsupportedEventTypeException.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelEventTest.java
src/test/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelCompositionDefinedEvent.json
src/test/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelCompositionDefinedEvent_without_meta.json

Previously we (thought we) used some clever Jackson tricks to deserialize an arbitrary Eiffel event JSON string into a instance of the correct class based on the event type declared in the meta section of the event by using the following EiffelEvent class annotations:
```Java
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME,
include = JsonTypeInfo.As.PROPERTY,
property = "meta.type")
@JsonSubTypes({
@JsonSubTypes.Type(value = EiffelActivityCanceledEvent.class,
name = "EiffelActivityCanceledEvent"),
...
})
```
This appeared to work, but:
- Jackson doesn't actually support nested field references (not with      this notation anyway). See e.g. https://stackoverflow.com/a/48467746.
- When serializing objects we got an unwanted "meta.type" key in the      resulting JSON payload. This could possibly be …

Fix broken JSON deserialization

---

README.md
pom.xml
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/BuildWithEiffelLinksAction.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/BuildWithEiffelLinksActionFreeStyleFactory.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/BuildWithEiffelLinksActionWorkflowFactory.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelCause.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/QueueListenerImpl.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/BuildWithEiffelLinksActionTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/QueueListenerImplTest.java

A new EiffelCause cause containing Eiffel event links is recognized the queue listener and populates the ActT event.
The new $JOB_URL/eiffel/build API endpoint complements the regular /build endpoint but also recognizes an "eiffellinks" key that, specified, gets parsed and ends up in the EiffelCause passed to started build. This allows clients to add e.g. CONTEXT and CAUSE to the Jenkins-originating activities.
There's one known bug/limitation: The EiffelCause class doesn't `@Export` list of links, only the short description. This shouldn't be a problem since the equivalent information is available from the events stored in the EiffelActivityAction that's also connected    to the run.
Closes #9.

Add EiffelCause and $JOB_URL/eiffel/build API endpoint

---

src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelJobTable.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/QueueListenerImpl.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/RunListenerImpl.java

This commit stack makes various improvements to EiffelJobTable and its call sites, including but not limited to making the class thread-safe and getting rid of the memory leak (which fixes #22). Looking at the whole PR at once will not make much sense but I've made the commits quite small and self-contained so I strongly recommend looking at them one by one.

EiffelJobTable: Make it thread-safe, fix memory leak, and clean it up in general

---

src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelBroadcasterConfig.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/JenkinsSourceProvider.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/SourceProvider.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/JenkinsSourceProviderTest.java

We populated meta.source.name earlier too but with a made-up string that wasn't used anywhere else. Use the plugin's long name instead (currently "Eiffel Broadcaster Plugin").
To avoid Jenkins dependencies in the Eiffel POJOs as well as not having to make separate calls to populate the meta.source members each time an event instance is created we let the event package define a SourceProvider interface that clients can set to an environment-specific implementer. A SourceProvider reference is stored in a static member in the EiffelEvent class. Perhaps not super elegant but probably better than many other options.
Once the event versions have been updated to something that uses package URLs rather than GAVs (#36) I'll send a PR to populate the meta.source.serializer member too.

Populate meta.source.{host,name,uri}

---

src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelBroadcasterConfig.java

Use #get() or #getInstanceOrNull() depending on the context.

Replace deprecated Jenkins#getInstance() calls

---

src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityCanceledEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityFinishedEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityStartedEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityTriggeredEvent.java

Previously we were still emitting events from the Toulouse edition. Changing to current version of the Act* events won't matter in practice since the only differences are in meta.security and data.source.serializer, neither of which is currently populated. Fixes #6.

Update event versions to the Paris edition

---

README.md
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelEnvironmentContributor.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelEnvironmentContributorTest.java

The new pipeline step injects environment variables with the JSON payloads of run's activity events:
withEiffelEnv {
sh 'echo "Here is the trigger: $EIFFEL_ACTIVITY_TRIGGERED"'
}
Variables are provided for the ActT and ActS events. A new build wrapper provides the same functionality for freestyle jobs. Fixes #20.

Inject environment variables in all builds

---

pom.xml
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/JenkinsSourceProvider.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/JenkinsSourceProviderTest.java

The main point of including the package URL of this plugin is to get the plugin version which isn't included in meta.source.name or elsewhere.

Populate meta.source.serializer with the package URL of the plugin

---

src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelBroadcasterConfig.java

The string array containing the names of the acceptable URL schemes, EiffelBroadcasterConfig#schemes, was marked as "private final" which caused it to be serialized to the plugin's configuration file. No big deal, but it's wasteful and potentially confusing since the values aren't really configurable.
We make that attribute transient (i.e. XStream can deserialize into the attribute but will ignore it when serializing) and introduce a new ALLOWED_URL_SCHEMES constant that won't be serialized (since it's static).

Don't include URL schemes array in serialized configuration

---

pom.xml

The pom.xml file contained a number of lines that were unnecessary because they were unused or superfluous given what's in the parent POM. The lines were most likely just copied from another (possibly much older) plugin when this plugin was initially set up.

Remove unnecessary lines from pom.xml

---

src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelBroadcasterConfig.java

Attempting to serialize EiffelBroadcasterConfig#eventValidator will blow up since one of the Jackson classes isn't deemed safe for serialization, and that's totally fine. The EventValidator instance wasn't meant to be serialized anyway.
This has been broken since commit e8171f6 but wasn't discovered since no tests attempt to save the configuration to disk (maybe they should?) and no manual testing prompted a configuration save.
Perhaps the event validator should be its own singleton instead of piggy-packing on the EiffelBroadcasterConfig singleton. Let's think about that when we revamp EiffelBroadcasterConfig to not extend the deprecated Plugin class.

Fix bug that broke configuration serialization

---

README.md
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelArtifactPublisher.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelArtifactToPublishAction.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EmptyArtifactException.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/MissingArtifactException.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/RunListenerImpl.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Util.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelArtifactCreatedEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelArtifactPublishedEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/PublishEiffelArtifactsStep.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/SendEiffelEventStep.java
src/main/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/PublishEiffelArtifactsStep/config.groovy
src/main/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/PublishEiffelArtifactsStep/help-artifactEventFiles.html
src/main/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/PublishEiffelArtifactsStep/help.html
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelArtifactPublisherTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EventSet.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/PublishEiffelArtifactsStepTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/SendEiffelEventStepTest.java
src/test/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/failed_publish_artifact_step_from_file_bad_type.groovy
src/test/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/successful_publish_artifact_step.groovy
src/test/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/successful_publish_artifact_step_from_file.groovy
src/test/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/successful_send_event_step_with_artifacts.groovy

If ArtC and ArtP are sent together during the build, consumers are susceptible to races since the Jenkins artifact URIs in the ArtP might not be available (since artifact archival is usually done at the very end of the build).
The new publishArtifact argument to the sendEiffelEvent step records the ArtC in the Run and a subsequent call to publishEiffelArtifact when the Jenkins artifacts have been made available (typically by using the archiveArtifacts step) will construct and send ArtP event(s) based on the ArtC events.
Sometimes the artifact creations are buried deep inside build scripts and calling the sendEiffelEvent pipeline step with publishArtifact set isn't possible.
To support that use case we add an artifactEventFiles argument to the publishEiffelArtifacts step. It contains an …

Send ArtP based on ArtC emitted during the build

---

src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/BuildWithEiffelLinksAction.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/BuildWithEiffelLinksActionTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Matchers.java

The logic in BuildWithEiffelLinksAction#getParametersAction was deeply flawed when the build request didn't provide values for all parameters defined for the job; default values were only included for all parameters if the build request didn't contain _any parameters at all_ but _never_ otherwise. We now make sure to always add default values for parameters that weren't present in the request.

Always add default values for missing params given in $BUILD_URL/eiffel/build request

---

src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/JenkinsSourceProvider.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelEvent.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/JenkinsSourceProviderTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelEventTest.java
src/test/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelActivityTriggeredEvent.json
src/test/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityTriggeredEvent.json

Previously the meta.source fields were only populated when an event class was instantiated directly, i.e. if the event was created by code in the plugin. Event objects created by the sendEiffelEvent pipeline step never asked the configured SourceProvider to populate meta.source.
The reason for this bug is that it was the EiffelEvent class that called the SourceProvider, but this was only done in the constructor. When deserializing JSON into an object the EiffelEvent#meta attribute is overwritten by Jackson after the event object is initialized, hence overwriting the SourceProvider-created value with the (possibly empty) EiffelEvent.Meta object created by Jackson.
We addresss this by changing the custom deserializer to ask EiffelEvent to populate meta.source after an event object has been …

Populate meta.source for events sent via the sendEiffelEvent pipeline step

---

src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityFinishedEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityStartedEvent.java

The toString() method had inadvertently been left out from EiffelActivityStartedEvent.Data.LiveLogs and EiffelActivityFinishedEvent.Data.PersistentLogs.

Add missing toString() methods

---

pom.xml
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelBroadcasterConfig.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/ItemListenerImpl.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/JenkinsSourceProvider.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Util.java
src/main/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelBroadcasterConfig/config.groovy
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/BuildWithEiffelLinksActionTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/ConfigurationAsCodeTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelEnvironmentContributorTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EmittedEventsTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/JenkinsSourceProviderTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/RestoreSourceProviderJenkinsConfiguredWithCodeRule.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/RestoreSourceProviderJenkinsRule.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/CreatePackageURLStepTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/PublishEiffelArtifactsStepTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/SendEiffelEventStepTest.java
src/test/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/jcasc-expected-output.yml
src/test/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/jcasc-input.yml

As a cleanup we convert EiffelBroadcasterConfig from extending the deprecated Plugin class to GlobalConfiguration and make the few adjustments required by that change, including:
- Using a different way of obtaining the plugin's Plugin or PluginWrapper instances since Jenkins#getPlugin only works for plugins that extend Plugin.
- Renaming the getter for EiffelBroadcasterConfig#enableBroadcaster so JCasC can find it.
Another complication of the switch from Plugin to GlobalConfiguration was that the assignment to the static EiffelEvent#sourceProvider attribute for some reason wasn't reset as it used to be. After a test that used JenkinsRule was run the attribute still pointed to a JenkinsSourceProvider instance that required a Jenkins instance to be present. I'm not sure exactly what …

Add JCasC support and modernize to extend from GlobalConfiguration instead of Plugin

---

src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Util.java

This should fix bug discussed in issue #4 where conclusion set to `null` when build state not recognized by the translation table due to incorrect key.

Fix result translate to null bug in Util.java

---

src/main/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelBroadcasterConfig/config.groovy

As a first step towards #69, move several of the available configuration options behind an Advanced button. They're "expert" options with reasonable default values, i.e. a first-time user shouldn't have to spend time on them.
Ideally the routing key option should be hidden too, but we can't do that until its default value has been overhauled.

Hide non-essential configuration options behind an Advanced button

---

README.md

README.md incorrectly referenced the wrong event type in the description of the publishEiffelArtifacts pipeline step.

Docs: Fix incorrect event type reference

---

src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/BuildWithEiffelLinksAction.java

An extremely unlikely but not impossible NPE in BuildWithEiffelLinksAction#getParametersAction is addressed. If the code is refactored those odds could change for the worse. Also, a future SpotBugs release will complain about this.

BuildWithEiffelLinksAction: Fix possible NPE

---

pom.xml
src/main/resources/index.jelly

The minimum required Jenkins version is updated to 2.303.3 (which is about a year old), and the BOM reference is updated accordingly. The parent POM is updated to the latest possible given the Jenkins version. Also, more plugins are now available in the BOM so a number of version references could be removed.
Finally, the plugin description must now reside in index.jelly; not the <description> element in the POM nor index.groovy. As per the [current recommendations](https://www.jenkins.io/doc/developer/tutorial-improve/move-description-to-index/) the description in the POM is removed, but that description text was much better than the one in index.groovy so let's copy it into the newly created index.jelly.

Upgrade Jenkins to 2.303.3

---

src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/MQConnection.java

For some time there's been a race condition during Jenkins startup between the sending of the first event and the initialization of the message queue thread.
The AMQP configuration is passed to MQConnection via initialized(), called from EiffelBroadcasterConfig#configure(). Until this has happened, the MQConnection's AMQP URL will be null and any attempt to send an event will trigger an NPE. To make matters worse, the message queue thread startup code in MQConnection#addMessageToQueue() had a bug it would attempt to restart a crashed thread rather than create a new one, resulting in an IllegalStateException.
We solve this by introducing an MQConnection#initialized attribute that's set to true only after we've received the configuration, and until then the message queue thread won't be …

Fix startup race condition that put the outbound message queue in a bad state

---

Jenkinsfile
pom.xml
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/MQConnection.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/ConnectionIntegrationTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/TestUtil.java

Improves the reliability and performance of message publishing in multiple ways, e.g. by introducing publisher confirms and asynchronous acks. Also adds integration tests for these operations using the testcontainers library.
This patch series is a reworked adaptation of what @hampusjohansson1 did in https://github.com/jenkinsci/mq-notifier-plugin/pull/30 and a few follow-up PRs. Fixup commits have been squashed into the original commits where the fixes belonged to make this series less noisy. Still, there are a few commits that change some things back and forth so reviewing the PR commit-by-commit might be more work. The resulting MQConnection.java (where nearly all the changes take place, except the new tests) is very close to the corresponding file in the MQ Notifier plugin. 
There are …

Make event publishing more reliable

---

pom.xml

Apart from just a general upgrade JMockit including various [bugfixes and new features](https://jmockit.github.io/changes.html), we now won't have to see a (harmless) NPE stacktrace in the build log.

pom.xml: Upgrade JMockit to 1.49

---

README.md

In #93 where we added support for events from the Orizaba edition we forgot to update the documentation accordingly to state this fact.
None.
```[tasklist]
```

README: State that we now support up to and including Orizaba

---

pom.xml
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelBroadcasterConfig.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Util.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/routingkeys/FixedRoutingKeyProvider.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/routingkeys/RoutingKeyProvider.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/routingkeys/SepiaRoutingKeyProvider.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/routingkeys/SepiaRoutingKeyProviderConfigurator.java
src/main/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelBroadcasterConfig/config.groovy
src/main/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/routingkeys/FixedRoutingKeyProvider/config.jelly
src/main/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/routingkeys/SepiaRoutingKeyProvider/config.jelly
src/main/webapp/FixedRoutingKeyProvider/help-fixed-routing-key.html
src/main/webapp/SepiaRoutingKeyProvider/help-tag.html
src/main/webapp/help-routing-key-provider.html
src/main/webapp/help-routing-key.html
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/ConfigurationAsCodeTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/routingkeys/SepiaRoutingKeyProviderTest.java
src/test/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/jcasc-expected-output.yml
src/test/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/jcasc-input-with-fixed-routing-key-provider.yml
src/test/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/jcasc-input-with-legacy-routing-key.yml
src/test/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/jcasc-input-with-sepia-routing-key-provider.yml
src/test/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/jcasc-input-without-routing-key-provider.yml

Having all events sent with the same fixed routing key can force consumers to consume more than they want to. Since a few years, Sepia contains a recommended routing key format that we should be able to conform to.
To ensure a smooth migration path for everyone, we replace the EiffelBroadcasterConfig#routingKey string field with a new #routingKeyProvider attribute that contains a subclass of RoutingKeyProvider. We ship the plugin with two such implementations; FixedRoutingKeyProvider that's equivalent to the legacy behavior, and SepiaRoutingKeyProvider that follows Sepia. Old Jenkins instances will get migrated to FixedRoutingKeyProvider while new ones get SepiaRoutingKeyProvider by default. Other plugins may supply their own implementations.
Fixes #69
Manual tests of the functionality. …

Introduce pluggable routing keys and Sepia conformance

---

src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelBroadcasterConfig.java

Commit bcc78f2 mistakenly introduced a Javadoc markup bug (`@see` was used instead of `@link`) which wasn't discovered until Javadoc was run during the release process for 2.7.0.
We should run "mvn javadoc:javadoc" during the pre-merge CI execution but we're inheriting its configuration so it's not immediately clear how to accomplish this.
Verified that `mvn javadoc:javadoc` passes with this correction (but not without it). It's a minor change in the Javadoc markup so I haven't tested anything else.
```[tasklist]
```

Correct bad Javadoc syntax that prevented 2.7.0 release

---

src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelEvent.java

This is the first commit in a stack that will address #99. Previously the event POJOs didn't contain any representation of meta.security. That was done because of the lack of support for signing. However, meta.security isn't entirely useless without signing, and with signing support planned for a follow-up commit we'll expand the event model already now.
- Verified by hand that serialization of a few event POJOs produces the expected JSON.
- In a follow-up commit that adds signing support I've verified a signed payload against code written with the Go SDK, which implies that the serialization is correct.
```[tasklist]
```

EiffelEvent: Add class attributes for meta.security

---

src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/BuildWithEiffelLinksActionTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/ConfigurationAsCodeTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/ConnectionIntegrationTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelArtifactPublisherTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelEnvironmentContributorTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EmittedEventsTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/JenkinsSourceProviderTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/QueueListenerImplTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/UtilTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelEventTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/GenericEiffelEventTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/PublishEiffelArtifactsStepTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/SendEiffelEventStepTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/routingkeys/SepiaRoutingKeyProviderTest.java

Wildcard imports came up during the review of #103. Getting rid of them altogether now.
All automatic tests pass. Commit only affects tests and shouldn't affect the resulting byte code at all.
```[tasklist]
```

Replace all wildcard imports with explicit imports

---

README.md

The documentation in README.md didn't state clearly that the sendEiffelEvent pipeline step returns the event that was sent (but the code example indicated that such was the case).
None; it's just a change in the Markdown prose.
```[tasklist]
```

README: Clarify that sendEiffelEvent returns the sent event

---

src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/JobCreatingJenkinsRule.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/PublishEiffelArtifactsStepTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/SendEiffelEventStepTest.java

We had duplicated code for creating a pipeline job and loading the pipeline code from a resource file. This wasn't too bad, but in the follow-up commit that'll conclude #99 we're planning to create such jobs in subfolders, which would make the problem worse. To reduce future pain we extract the code to methods in a new JenkinsRule subclass.
Its name, JobCreatingJenkinsRule, isn't very imaginative but maybe it's descriptive. If we want to widen the scope in the future it's easy enough to rename it.
Changes only affect tests so I've only verified that they still work.
```[tasklist]
```

Create new JenkinsRule subclass to reduce duplication

---

src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/HashAlgorithm.java

When HashAlgorithm#fromString() was added in commit e17030e, we also added #toString(), perhaps in some kind of misguided desire for symmetry. Unfortunately, this prevented Stapler from serializing HashAlgorithm values since #toString() would return e.g. "SHA-256" which obviously doesn't match any of the enum values.
This is a bugfix for the work in #99.
Apart from running all tests I tested that saving the system configuration page worked (that's what failed prior to this commit). Also verified that system events as well as user events are sent.
```[tasklist]
```

HashAlgorithm: Remove #toString() so Stapler can serialize again

---

src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/signing/CredentialChangeListener.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/signing/SigningKeyCache.java

Although we currently have a rather short TTL for the signature key cache (60 s), as a user I'd expect changes in credentials to take effect immediately. With a SaveableListener it's easy to trigger a flush of the cache when it's the SystemCredentialsProvider's XML file that changed.
This finally closes #99.
Automatic tests pass. Also tested manually that the cache clears after the credentials are modified.
```[tasklist]
```

Invalidate signature key cache when credentials change

---

pom.xml

Standard, no-frills upgrade of the base Jenkins version and the plugin POM. Apart from being generally sane, it'll allow us to upgrade com.networknt:json-schema-validator to a version that supports draft 2020-12 of the JSON schema metaschema.
We were also able to remove a no longer necessary version override for workflow-cps that was introduced in commit ac48793, plus an orphaned property (jenkins-test-harness.version).
All tests pass, local smoke test doesn't indicate any problems.

pom.xml: Upgrade parent POM and base Jenkins version to 2.426.3

---

README.md
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/PublishEiffelArtifactsStep.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/PublishEiffelArtifactsStepTest.java
src/test/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/successful_publish_artifact_step_with_payloads_saved.groovy

Similar to how the sendEiffelEvent step already works, the publishEiffelArtifacts step now returns a list of the published events.
Manual happy testing performed and all automated tests pass (including the test I added for this particular feature).

publishEiffelArtifacts: Return published artifact events

---

src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/QueueListenerImplTest.java

When we converted all code to use local variable type inference as much as possible in #105, it seems we simply forgot about QueueListenerImplTest. That was unintentional.
No functional changes, not even in the tests. But they pass.

QueueListenerImplTest: Use local variable type inference

---

README.md
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/build/BuildWithEiffelStep.java
src/main/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Messages.properties
src/main/resources/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/build/BuildWithEiffelStep/help.html
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/build/BuildWithEiffelStepRegressionTest.java

Resolves #118
Replaced inheritance of BuildTriggerStep and its descriptor with modified copied code from the class itself to avoid breaking the pipeline step document generator. Inheritance of a descriptor from another step is not supported by the generator and we might as well get rid off the Step inheritance to remove any dependencies towards BuildTriggerStep.

Replace inheritance in BuildWithEiffelStep

---

src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelArtifactPublisher.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelBroadcasterConfig.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/QueueListenerImpl.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/RunListenerImpl.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityCanceledEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityFinishedEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityStartedEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityTriggeredEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelArtifactCreatedEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelArtifactPublishedEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelEvent.java
src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelEventFactory.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/BuildWithEiffelLinksActionTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelArtifactPublisherTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EmittedEventsTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/JenkinsSourceProviderTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/QueueListenerImplTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/SourceProviderResetter.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/TestUtil.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelEventSigningTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelEventTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EventValidatorTest.java
src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/routingkeys/SepiaRoutingKeyProviderTest.java

This is a first step towards #62 (which, in turn, enables supporting newer protocol features like the ORIGINAL_TRIGGER link type). Previously each event class has hardcoded its version. We want to support central configuration of the Eiffel edition to use for outbound events, and to avoid having a dependency to that configuration from each event class we introduce a factory class. Right now the factory only has a hardcoded event table, but that'll change in a follow-up commit.
We also move the SourceProvider from EiffelEvent to EiffelEventFactory, making the event classes pure POJOs.
The drawback of the factory is that the classes are dumb in the sense that their constructors no longer take parameters for mandatory fields, i.e. it's less obvious what input you really need to provide to …

Replace manual event instantiation with EiffelEventFactory

---

README.md

Clarify the documentation of how to generate a certificate using OpenSSL, primarily that the RDNs are expected to be listed in the opposite order compared to e.g. Jenkins itself.
None. This is a pure documentation change.

README: Clarify the subject DN format expected by OpenSSL
